### ISSUE TITLE
how to add AuthorityKeyIdentifier extension to selfsignedcertificate

### ISSUE THREAD

**Issue by github-amazingboy** [PeculiarVentures/PKI.js#206]
this is my code, but it display the value empty:
```javascript
var result = await crypto.digest({ name: "SHA-1" }, this.certificate.subjectPublicKeyInfo.subjectPublicKey.valueBlock.valueHex);

        var keyIDExtension = new Extension({
            extnID: "2.5.29.14",
            critical: false,
            extnValue: new OctetString({ valueHex: result }).toBER(false)
        });
        var issuerKeyIDExtension = new Extension({
            extnID: "2.5.29.35",
            critical: false,
            extnValue: new AuthorityKeyIdentifier({
                keyIdentifier:new OctetString({ valueHex: result })
            }).toSchema().toBER(false)
        });
        await this.certificate.extensions.push(issuerKeyIDExtension);       
        await this.certificate.extensions.push(keyIDExtension);
```

**Comment by YuryStrozhevsky** [comment]
@github-amazingboy Thanks for the issue, there were a number of problems in `AuthorityKeyIdentifier` class. Now it is fixed.

And you do not need `await` in least two lines: the `extensions` variable is a simple JavaScript `Array`, nothing else.

**Comment by github-amazingboy** [comment]
good, now it run very well. 
PKI.js is a great project. It covers almost all PKI. but I still have some suggestion:

1.  I do not know which IDE the author use. it is not intellisense in VSCode. I was miserable. 
     such as:   this.certificate.subjectPublicKeyInfo.subjectPublicKey.valueBlock.valueHex
    maybe it should Encapsulation. after all, not every caller needs to understand the underlying implementation.
     if I need to jump the PKI source , the VSCode cannot do it. 
     every time I find it in node_modules/pkijs/xxx.js

2. the example is very useful for the people not know PKI. but there is a problem. it use the Promise, then, I donot know which place should await, I donot know which is an async function. importKey/sign/digest ???

3. I hope the new version can use typescript. it will constraint the type when I write it.

English is not good , hope you can get it. (some translate by google)

**Comment by YuryStrozhevsky** [comment]
1. JetBrains WebStorm
2. All after “return” or after “=>” should be under “await”
3. There are no plans for typescript version mostly because I don’t believe in the language and don’t like it

**Comment by rmhrisk** [comment]
Thanks for the great feedback @github-amazingboy

**Comment by github-amazingboy** [comment]
@YuryStrozhevsky @rmhrisk  thanks for your reply
